list = {};                  //Object with characters in there

list.characters = [{
  'id'          :   [00],
  'name'        :   ["alex"],
  'gender'      :   ["man"],
  'picture'     :   ["images/bill.png"],
  'head'        :   ["round"],
  'nose'        :   ["small"],
  'hair'        :   ["orange","bold"],
  'expresion'   :   ["smile","grin"],
  'cheeks'      :   ["thick","red"]  
},
{
  'id'          :   [01],
  'name'        :   ["alfred"],
  'gender'      :   ["man"],
  'picture'     :   ["images/anita.png"],
  'head'        :   ["pear shaped"],
  'nose'        :   ["small"],
  'hair'        :   ["orange","bold"],
  'expresion'   :   ["grin"],
  'cheeks'      :   ["thick","red"]  
},
{
  'id'          :   [02],
  'name'        :   ["anita"],
  'gender'      :   ["woman"],
  'picture'     :   ["images/anita.png"],
  'head'        :   ["pear shaped"],
  'nose'        :   ["small"],
  'hair'        :   ["orange","bold"],
  'expresion'   :   ["grin"],
  'cheeks'      :   ["thick","red"]  
},{
  'id'          :   [03],
  'name'        :   ["anne"],
  'gender'      :   ["woman"],
  'picture'     :   ["images/bill.png"],
  'head'        :   ["round"],
  'nose'        :   ["small"],
  'hair'        :   ["orange","bold"],
  'expresion'   :   ["smile","grin"],
  'cheeks'      :   ["thick","red"]  
},
{
  'id'          :   [04],
  'name'        :   ["bernard"],
  'gender'      :   ["man"],
  'picture'     :   ["images/anita.png"],
  'head'        :   ["pear shaped"],
  'nose'        :   ["small"],
  'hair'        :   ["orange","bold"],
  'expresion'   :   ["grin"],
  'cheeks'      :   ["thick","red"]  
},
{
  'id'          :   [05],
  'name'        :   ["bill"],
  'gender'      :   ["man"],
  'picture'     :   ["images/anita.png"],
  'head'        :   ["pear shaped"],
  'nose'        :   ["small"],
  'hair'        :   ["orange","bold"],
  'expresion'   :   ["grin"],
  'cheeks'      :   ["thick","red"]  
},
{
  'id'          :   [06],
  'name'        :   ["charles"],
  'gender'      :   ["man"],
  'picture'     :   ["images/anita.png"],
  'head'        :   ["pear shaped"],
  'nose'        :   ["small"],
  'hair'        :   ["orange","bold"],
  'expresion'   :   ["grin"],
  'cheeks'      :   ["thick","red"]  
},
{
  'id'          :   [07],
  'name'        :   ["claire"],
  'gender'      :   ["woman"],
  'picture'     :   ["images/anita.png"],
  'head'        :   ["pear shaped"],
  'nose'        :   ["small"],
  'hair'        :   ["orange","bold"],
  'expresion'   :   ["grin"],
  'cheeks'      :   ["thick","red"]  
},
{
  'id'          :   [08],
  'name'        :   ["david"],
  'gender'      :   ["man"],
  'picture'     :   ["images/bill.png"],
  'head'        :   ["round"],
  'nose'        :   ["small"],
  'hair'        :   ["orange","bold"],
  'expresion'   :   ["smile","grin"],
  'cheeks'      :   ["thick","red"]  
},
{
  'id'          :   [09],
  'name'        :   ["eric"],
  'gender'      :   ["man"],
  'picture'     :   ["images/anita.png"],
  'head'        :   ["pear shaped"],
  'nose'        :   ["small"],
  'hair'        :   ["orange","bold"],
  'expresion'   :   ["grin"],
  'cheeks'      :   ["thick","red"]  
},
{
  'id'          :   [10],
  'name'        :   ["frans"],
  'gender'      :   ["man"],
  'picture'     :   ["images/frans.png"],
  'head'        :   ["pear shaped"],
  'nose'        :   ["small"],
  'hair'        :   ["orange","bold"],
  'expresion'   :   ["grin"],
  'cheeks'      :   ["thick","red"]  
},
{
  'id'          :   [11],
  'name'        :   ["george"],
  'gender'      :   ["man"],
  'picture'     :   ["images/george.png"],
  'head'        :   ["round"],
  'nose'        :   ["small"],
  'hair'        :   ["orange","bold"],
  'expresion'   :   ["smile","grin"],
  'cheeks'      :   ["thick","red"]  
},
{
  'id'          :   [12],
  'name'        :   ["herman"],
  'gender'      :   ["man"],
  'picture'     :   ["images/herman.png"],
  'head'        :   ["pear shaped"],
  'nose'        :   ["small"],
  'hair'        :   ["orange","bold"],
  'expresion'   :   ["grin"],
  'cheeks'      :   ["thick","red"]  
},
{
  'id'          :   [13],
  'name'        :   ["joe"],
  'gender'      :   ["man"],
  'picture'     :   ["images/joe.png"],
  'head'        :   ["pear shaped"],
  'nose'        :   ["small"],
  'hair'        :   ["orange","bold"],
  'expresion'   :   ["grin"],
  'cheeks'      :   ["thick","red"]  
},
{
  'id'          :   [14],
  'name'        :   ["anne"],
  'gender'      :   ["woman"],
  'picture'     :   ["images/bill.png"],
  'head'        :   ["round"],
  'nose'        :   ["small"],
  'hair'        :   ["orange","bold"],
  'expresion'   :   ["smile","grin"],
  'cheeks'      :   ["thick","red"]  
},
{
  'id'          :   [15],
  'name'        :   ["max"],
  'gender'      :   ["man"],
  'picture'     :   ["images/max.png"],
  'head'        :   ["pear shaped"],
  'nose'        :   ["small"],
  'hair'        :   ["orange","bold"],
  'expresion'   :   ["grin"],
  'cheeks'      :   ["thick","red"]  
},
{
  'id'          :   [16],
  'name'        :   ["paul"],
  'gender'      :   ["man"],
  'picture'     :   ["images/paul.png"],
  'head'        :   ["pear shaped"],
  'nose'        :   ["small"],
  'hair'        :   ["orange","bold"],
  'expresion'   :   ["grin"],
  'cheeks'      :   ["thick","red"]  
},
{ 'id'          :   [17],
'name'        :   ["peter"],
'gender'      :   ["man"],
'picture'     :   ["images/peter.png"],
'head'        :   ["round"],
'nose'        :   ["small"],
'hair'        :   ["orange","bold"],
'expresion'   :   ["smile","grin"],
'cheeks'      :   ["thick","red"]  
},
{
  'id'          :   [18],
  'name'        :   ["philip"],
  'gender'      :   ["man"],
  'picture'     :   ["images/philip.png"],
  'head'        :   ["pear shaped"],
  'nose'        :   ["small"],
  'hair'        :   ["orange","bold"],
  'expresion'   :   ["grin"],
  'cheeks'      :   ["thick","red"]  
},
{
  'id'          :   [19],
  'name'        :   ["richard"],
  'gender'      :   ["wman"],
  'picture'     :   ["images/richard.png"],
  'head'        :   ["pear shaped"],
  'nose'        :   ["small"],
  'hair'        :   ["orange","bold"],
  'expresion'   :   ["grin"],
  'cheeks'      :   ["thick","red"]  
},
{
  'id'          :   [20],
  'name'        :   ["robert"],
  'gender'      :   ["man"],
  'picture'     :   ["images/robert.png"],
  'head'        :   ["round"],
  'nose'        :   ["small"],
  'hair'        :   ["orange","bold"],
  'expresion'   :   ["smile","grin"],
  'cheeks'      :   ["thick","red"]  
},
{ 'id'          :   [21],
'name'        :   ["sam"],
'gender'      :   ["man"],
'picture'     :   ["images/sam.png"],
'head'        :   ["pear shaped"],
'nose'        :   ["small"],
'hair'        :   ["orange","bold"],
'expresion'   :   ["grin"],
'cheeks'      :   ["thick","red"]  
},
{
  'id'          :   [22],
  'name'        :   ["susan"],
  'gender'      :   ["woman"],
  'picture'     :   ["images/susan.png"],
  'head'        :   ["pear shaped"],
  'nose'        :   ["small"],
  'hair'        :   ["orange","bold"],
  'expresion'   :   ["grin"],
  'cheeks'      :   ["thick","red"]  
},
{
  'id'          :   [23],
  'name'        :   ["tom"],
  'gender'      :   ["man"],
  'picture'     :   ["images/tom.png"],
  'head'        :   ["round"],
  'nose'        :   ["small"],
  'hair'        :   ["orange","bold"],
  'expresion'   :   ["smile","grin"],
  'cheeks'      :   ["thick","red"]  
}];


