list = {};                  //Object with characters in there

//Prints the adjectives
list.options =[{
  'gender'      :   ["gent", "lady"],
  'head'        :   ["square", "long", "oval", "round"],
  'nose'        :   ["small", "medium", "large", "extra large"],
  'ears'        :   ["small","normal", "big"],
  'eyes'        :   ["brown","blue","bushy eyebrows", "neat eyebrows", "normal eyebrows"],
  'cheeks'      :   ["rosy"],
  'chin'        :   ["dimple", "pointy", "round"],
  'mouth'       :   ["wide", "small", "small lips", "big lips"], 
  'hair'        :   ["black","blonde","white","ginger","short", "long", "bald"],
  'expresion'   :   ["neutral","happy","grumpy","pout"],
  'facial hair' :   ["moustache", "beard"],
  'accessories' :   ["hat","earring","glasses","bows"]  
}]

//Generates Questions for the computer
list.computerQuestions = {
  1 : [{
        feature: "gender",
        adjectives: ["gent", "lady"]
      }],
  2 : [{
        feature: "eyes",
        adjectives: ["brown","blue"]
      },
      {
        feature: "nose",
        adjectives: ["large", "extra large"]
      },
      {
        feature: "cheeks",
        adjectives: ["rosy"]
      }],
  3 : [{
        feature: "hair",
        adjectives: ["black","blonde","white","ginger"]
      },
      { 
        feature: "mouth",
        adjectives: ["wide", "small", "small lips", "big lips"]
      }],
  4 : [{
        feature: 'accessories',
        adjectives: ["hat","glasses"]
      },
      { 
        feature: 'expresion',
        adjectives: ["grumpy","pout","happy"]
      }],
  5 : [{
        feature: 'accessories',
        adjectives: ["earring","bows"]
      }]
}

//List for the computer to guess from
list.charactersNames = ["alex", "alfred", "anita", "anne", "bernard", "bill", "charles", "claire", "david", "eric", "frans", "george", "herman", "joe", "maria", "max", "paul", "peter", "philip", "richard", "robert", "sam","susan", "tom"]


//List for the computer to check the adjectives
list.computerCharacters = {
  "alex": {
            'id'          :   [00],
            'name'        :   ["alex"],
            'gender'      :   ["gent"],
            'picture'     :   ["pictures/alex.png"],
            'head'        :   ["square"],
            'nose'        :   ["small"],
            'ears'        :   ["big"],
            'eyes'        :   ["brown", "neat eyebrows"],
            'cheeks'      :   ["none"],
            'chin'        :   ["dimple"],
            'mouth'       :   ["wide", "big lips"], 
            'hair'        :   ["black","short"],
            'expresion'   :   ["neutral"],
            'facial hair' :   ["moustache"],
            'accessories' :   ["none"]  
          },
  "alfred": {
            'id'          :   [01],
            'name'        :   ["alfred"],
            'gender'      :   ["gent"],
            'picture'     :   ["pictures/alfred.png"],
            'head'        :   ["long"],
            'nose'        :   ["medium"],
            'ears'        :   ["big"],
            'eyes'        :   ["bleu", "neat eyebrows"],
            'cheeks'      :   ["none"],
            'chin'        :   ["pointy"],
            'mouth'       :   ["narrow", "small lips"], 
            'hair'        :   ["ginger","long"],
            'expresion'   :   ["grumpy", "pout"],
            'facial hair' :   ["moustache"],
            'accessories' :   ["none"]  
          },
  "anita": {
            'id'          :   [02],
            'name'        :   ["anita"],
            'gender'      :   ["lady"],
            'picture'     :   ["pictures/anita.png"],
            'head'        :   ["oval"],
            'nose'        :   ["small"],
            'ears'        :   ["none"],
            'eyes'        :   ["blue", "neat eyebrows"],
            'cheeks'      :   ["rosy"],
            'chin'        :   ["pointy"],
            'mouth'       :   ["narrow", "small lips"], 
            'hair'        :   ["blonde","long"],
            'expresion'   :   ["happy"],
            'facial hair' :   ["none"],
            'accessories' :   ["bows"]  
          },
  "anne": {
            'id'          :   [03],
            'name'        :   ["anne"],
            'gender'      :   ["lady"],
            'picture'     :   ["pictures/anne.png"],
            'head'        :   ["round"],
            'nose'        :   ["large"],
            'ears'        :   ["none"],
            'eyes'        :   ["brown", "neat eyebrows"],
            'cheeks'      :   ["none"],
            'chin'        :   ["round"],
            'mouth'       :   ["narrow", "small lips"], 
            'hair'        :   ["black","short"],
            'expresion'   :   ["pout"],
            'facial hair' :   ["none"],
            'accessories' :   ["earring"]  
          },
  "bernard": {
            'id'          :   [04],
            'name'        :   ["bernard"],
            'gender'      :   ["gent"],
            'picture'     :   ["pictures/bernard.png"],
            'head'        :   ["oval"],
            'nose'        :   ["extra large"],
            'ears'        :   ["big"],
            'eyes'        :   ["brow", "normal eyebrows"],
            'cheeks'      :   ["none"],
            'chin'        :   ["dimple"],
            'mouth'       :   ["narrow", "small lips"], 
            'hair'        :   ["brown","short"],
            'expresion'   :   ["grumpy"],
            'facial hair' :   ["none"],
            'accessories' :   ["hat"]  
          },
  "bill": {
            'id'          :   [05],
            'name'        :   ["bill"],
            'gender'      :   ["gent"],
            'picture'     :   ["pictures/bill.png"],
            'head'        :   ["egg shaped"],
            'nose'        :   ["small"],
            'ears'        :   ["normal"],
            'eyes'        :   ["brown", "normal eyebrows"],
            'cheeks'      :   ["rosy"],
            'chin'        :   ["none"],
            'mouth'       :   ["narrow", "small lips"], 
            'hair'        :   ["ginger","bald"],
            'expresion'   :   ["happy"],
            'facial hair' :   ["beard"],
            'accessories' :   ["none"]  
          },
  "charles": {
            'id'          :   [06],
            'name'        :   ["charles"],
            'gender'      :   ["gent"],
            'picture'     :   ["pictures/charles.png"],
            'head'        :   ["round"],
            'nose'        :   ["medium"],
            'ears'        :   ["big"],
            'eyes'        :   ["brown", "normal eyebrows"],
            'cheeks'      :   ["none"],
            'chin'        :   ["round"],
            'mouth'       :   ["wide", "big lips"], 
            'hair'        :   ["blonde","short"],
            'expresion'   :   ["happy"],
            'facial hair' :   ["moustache"],
            'accessories' :   ["none"]  
          },
  "claire": {
            'id'          :   [07],
            'name'        :   ["claire"],
            'gender'      :   ["lady"],
            'picture'     :   ["pictures/claire.png"],
            'head'        :   ["oval"],
            'nose'        :   ["small"],
            'ears'        :   ["none"],
            'eyes'        :   ["brown", "neat eyebrows"],
            'cheeks'      :   ["none"],
            'chin'        :   ["round"],
            'mouth'       :   ["narrow", "small lips"], 
            'hair'        :   ["ginger","short"],
            'expresion'   :   ["pout"],
            'facial hair' :   ["none"],
            'accessories' :   ["hat", "glasses"]  
          },
  "david": {
            'id'          :   [08],
            'name'        :   ["david"],
            'gender'      :   ["gent"],
            'picture'     :   ["pictures/david.png"],
            'head'        :   ["long"],
            'nose'        :   ["small"],
            'ears'        :   ["big"],
            'eyes'        :   ["brown", "normal eyebrows"],
            'cheeks'      :   ["none"],
            'chin'        :   ["none"],
            'mouth'       :   ["wide", "small lips"], 
            'hair'        :   ["blonde","short"],
            'expresion'   :   ["happy"],
            'facial hair' :   ["beard"],
            'accessories' :   ["none"]  
          },
  "eric": {
            'id'          :   [09],
            'name'        :   ["eric"],
            'gender'      :   ["gent"],
            'picture'     :   ["pictures/eric.png"],
            'head'        :   ["square"],
            'nose'        :   ["small"],
            'ears'        :   ["normal"],
            'eyes'        :   ["brown", "normal eyebrows"],
            'cheeks'      :   ["none"],
            'chin'        :   ["dimple"],
            'mouth'       :   ["wide", "small lips"], 
            'hair'        :   ["blonde","short"],
            'expresion'   :   ["happy"],
            'facial hair' :   ["none"],
            'accessories' :   ["hat"]  
          },
  "frans": {
            'id'          :   [10],
            'name'        :   ["frans"],
            'gender'      :   ["gent"],
            'picture'     :   ["pictures/frans.png"],
            'head'        :   ["square"],
            'nose'        :   ["small"],
            'ears'        :   ["big"],
            'eyes'        :   ["brown", "bushy eyebrows"],
            'cheeks'      :   ["none"],
            'chin'        :   ["pointy"],
            'mouth'       :   ["narrow", "small lips"], 
            'hair'        :   ["ginger","short"],
            'expresion'   :   ["pout"],
            'facial hair' :   ["none"],
            'accessories' :   ["none"]  
          },
 "george": {
            'id'          :   [11],
            'name'        :   ["george"],
            'gender'      :   ["gent"],
            'picture'     :   ["pictures/george.png"],
            'head'        :   ["round"],
            'nose'        :   ["medium"],
            'ears'        :   ["normal"],
            'eyes'        :   ["brown", "normal eyebrows"],
            'cheeks'      :   ["none"],
            'chin'        :   ["dimple"],
            'mouth'       :   ["wide", "small lips"], 
            'hair'        :   ["white","short"],
            'expresion'   :   ["said"],
            'facial hair' :   ["none"],
            'accessories' :   ["hat"]  
          },
  "herman": {
            'id'          :   [12],
            'name'        :   ["herman"],
            'gender'      :   ["gent"],
            'picture'     :   ["pictures/herman.png"],
            'head'        :   ["oval"],
            'nose'        :   ["extra large"],
            'ears'        :   ["normal"],
            'eyes'        :   ["brown", "bushy eyebrows"],
            'cheeks'      :   ["none"],
            'chin'        :   ["pointy"],
            'mouth'       :   ["narrow", "small lips"], 
            'hair'        :   ["ginger","bald"],
            'expresion'   :   ["neutral"],
            'facial hair' :   ["none"],
            'accessories' :   ["none"]  
          },
  "joe":  {
            'id'          :   [13],
            'name'        :   ["joe"],
            'gender'      :   ["gent"],
            'picture'     :   ["pictures/joe.png"],
            'head'        :   ["oval"],
            'nose'        :   ["medium"],
            'ears'        :   ["normal"],
            'eyes'        :   ["brown", "bushy eyebrows"],
            'cheeks'      :   ["none"],
            'chin'        :   ["dimple"],
            'mouth'       :   ["narrow", "small lips"], 
            'hair'        :   ["blonde","short"],
            'expresion'   :   ["pout"],
            'facial hair' :   ["none"],
            'accessories' :   ["glasses"]  
          },
  "maria": {
            'id'          :   [14],
            'name'        :   ["maria"],
            'gender'      :   ["lady"],
            'picture'     :   ["pictures/maria.png"],
            'head'        :   ["oval"],
            'nose'        :   ["medium"],
            'ears'        :   ["none"],
            'eyes'        :   ["brown", "neat eyebrows"],
            'cheeks'      :   ["none"],
            'chin'        :   ["round"],
            'mouth'       :   ["wide", "small lips"], 
            'hair'        :   ["brown","long"],
            'expresion'   :   ["pout"],
            'facial hair' :   ["none"],
            'accessories' :   ["hat", "earring"]  
          },
  "max": {
            'id'          :   [15],
            'name'        :   ["max"],
            'gender'      :   ["gent"],
            'picture'     :   ["pictures/max.png"],
            'head'        :   ["round"],
            'nose'        :   ["extra large"],
            'ears'        :   ["normal"],
            'eyes'        :   ["brown", "normal eyebrows"],
            'cheeks'      :   ["none"],
            'chin'        :   ["none"],
            'mouth'       :   ["wide", "big lips"], 
            'hair'        :   ["black","short"],
            'expresion'   :   ["happy"],
            'facial hair' :   ["moustache"],
            'accessories' :   ["none"]  
          },
  "paul": {
            'id'          :   [16],
            'name'        :   ["paul"],
            'gender'      :   ["gent"],
            'picture'     :   ["pictures/paul.png"],
            'head'        :   ["oval"],
            'nose'        :   ["small"],
            'ears'        :   ["big"],
            'eyes'        :   ["brown", "normal eyebrows"],
            'cheeks'      :   ["none"],
            'chin'        :   ["dimple"],
            'mouth'       :   ["narrow", "small lips"], 
            'hair'        :   ["white","short"],
            'expresion'   :   ["happy"],
            'facial hair' :   ["none"],
            'accessories' :   ["glasses"]  
          },
  "peter": { 
            'id'          :   [17],
            'name'        :   ["peter"],
            'gender'      :   ["gent"],
            'picture'     :   ["pictures/peter.png"],
            'head'        :   ["square"],
            'nose'        :   ["extra large"],
            'ears'        :   ["normal"],
            'eyes'        :   ["blue", "bushy eyebrows"],
            'cheeks'      :   ["none"],
            'chin'        :   ["pointy"],
            'mouth'       :   ["wide", "big lips"], 
            'hair'        :   ["white","short"],
            'expresion'   :   ["happy"],
            'facial hair' :   ["none"],
            'accessories' :   ["none"]  
          },
  "philip": {
            'id'          :   [18],
            'name'        :   ["philip"],
            'gender'      :   ["gent"],
            'picture'     :   ["pictures/philip.png"],
            'head'        :   ["round"],
            'nose'        :   ["medium"],
            'ears'        :   ["normal"],
            'eyes'        :   ["brown", "need eyebrows"],
            'cheeks'      :   ["rosy"],
            'chin'        :   ["none"],
            'mouth'       :   ["wide", "small lips"], 
            'hair'        :   ["black","short"],
            'expresion'   :   ["happy"],
            'facial hair' :   ["beard"],
            'accessories' :   ["none"]  
          },
  "richard": {
          'id'          :   [19],
          'name'        :   ["richard"],
          'gender'      :   ["gent"],
          'picture'     :   ["pictures/richard.png"],
          'head'        :   ["long"],
          'nose'        :   ["medium"],
          'ears'        :   ["normal"],
          'eyes'        :   ["brown", "normal eyebrows"],
          'cheeks'      :   ["none"],
          'chin'        :   ["none"],
          'mouth'       :   ["narrow", "small lips"], 
          'hair'        :   ["brown","bald"],
          'expresion'   :   ["neutral"],
          'facial hair' :   ["moustache", "beard"],
          'accessories' :   ["none"]  
        },
  "robert": {
          'id'          :   [20],
          'name'        :   ["robert"],
          'gender'      :   ["gent"],
          'picture'     :   ["pictures/robert.png"],
          'head'        :   ["oval"],
          'nose'        :   ["extra large"],
          'ears'        :   ["big"],
          'eyes'        :   ["bleu", "normal eyebrows"],
          'cheeks'      :   ["rosy"],
          'chin'        :   ["dimple"],
          'mouth'       :   ["wide", "small lips"], 
          'hair'        :   ["brown","short"],
          'expresion'   :   ["grumpy"],
          'facial hair' :   ["none"],
          'accessories' :   ["none"]   
        },
  "sam": { 
          'id'          :   [21],
          'name'        :   ["sam"],
          'gender'      :   ["gent"],
          'picture'     :   ["pictures/sam.png"],
          'head'        :   ["round"],
          'nose'        :   ["medium"],
          'ears'        :   ["small"],
          'eyes'        :   ["brown", "need eyebrows"],
          'cheeks'      :   ["none"],
          'chin'        :   ["pointy"],
          'mouth'       :   ["small", "small lips"], 
          'hair'        :   ["white","bald"],
          'expresion'   :   ["happy"],
          'facial hair' :   ["none"],
          'accessories' :   ["glasses"]  
        },
  "susan": {
          'id'          :   [22],
          'name'        :   ["susan"],
          'gender'      :   ["lady"],
          'picture'     :   ["pictures/susan.png"],
          'head'        :   ["oval"],
          'nose'        :   ["small"],
          'ears'        :   ["none"],
          'eyes'        :   ["brown", "need eyebrows"],
          'cheeks'      :   ["rosy"],
          'chin'        :   ["round"],
          'mouth'       :   ["wide", "big lips"], 
          'hair'        :   ["white","long"],
          'expresion'   :   ["happy"],
          'facial hair' :   ["none"],
          'accessories' :   ["none"]  
        },
  "tom": {
          'id'          :   [23],
          'name'        :   ["tom"],
          'gender'      :   ["gent"],
          'picture'     :   ["pictures/tom.png"],
          'head'        :   ["long"],
          'nose'        :   ["medium"],
          'ears'        :   ["normal"],
          'eyes'        :   ["blue", "normal eyebrows"],
          'cheeks'      :   ["none"],
          'chin'        :   ["round"],
          'mouth'       :   ["narrow", "small lips"], 
          'hair'        :   ["black","bald"],
          'expresion'   :   ["happy"],
          'facial hair' :   ["none"],
          'accessories' :   ["glasses"]  
        }
  };


//List for player to check the adjectives
list.characters = [{
  'id'          :   [00],
  'name'        :   ["alex"],
  'gender'      :   ["gent"],
  'picture'     :   ["pictures/alex.png"],
  'head'        :   ["square"],
  'nose'        :   ["small"],
  'ears'        :   ["big"],
  'eyes'        :   ["brown", "neat eyebrows"],
  'cheeks'      :   ["none"],
  'chin'        :   ["dimple"],
  'mouth'       :   ["wide", "big lips"], 
  'hair'        :   ["black","short"],
  'expresion'   :   ["neutral"],
  'facial hair' :   ["moustache"],
  'accessories' :   ["none"]  
},
{
  'id'          :   [01],
  'name'        :   ["alfred"],
  'gender'      :   ["gent"],
  'picture'     :   ["pictures/alfred.png"],
  'head'        :   ["long"],
  'nose'        :   ["medium"],
  'ears'        :   ["big"],
  'eyes'        :   ["bleu", "neat eyebrows"],
  'cheeks'      :   ["none"],
  'chin'        :   ["pointy"],
  'mouth'       :   ["narrow", "small lips"], 
  'hair'        :   ["ginger","long"],
  'expresion'   :   ["grumpy", "pout"],
  'facial hair' :   ["moustache"],
  'accessories' :   ["none"]  
},
{
  'id'          :   [02],
  'name'        :   ["anita"],
  'gender'      :   ["lady"],
  'picture'     :   ["pictures/anita.png"],
  'head'        :   ["oval"],
  'nose'        :   ["small"],
  'ears'        :   ["none"],
  'eyes'        :   ["blue", "neat eyebrows"],
  'cheeks'      :   ["rosy"],
  'chin'        :   ["pointy"],
  'mouth'       :   ["narrow", "small lips"], 
  'hair'        :   ["blonde","long"],
  'expresion'   :   ["happy"],
  'facial hair' :   ["none"],
  'accessories' :   ["bows"]  
},{
  'id'          :   [03],
  'name'        :   ["anne"],
  'gender'      :   ["lady"],
  'picture'     :   ["pictures/anne.png"],
  'head'        :   ["round"],
  'nose'        :   ["large"],
  'ears'        :   ["none"],
  'eyes'        :   ["brown", "neat eyebrows"],
  'cheeks'      :   ["none"],
  'chin'        :   ["round"],
  'mouth'       :   ["narrow", "small lips"], 
  'hair'        :   ["black","short"],
  'expresion'   :   ["pout"],
  'facial hair' :   ["none"],
  'accessories' :   ["earring"]  
},
{
  'id'          :   [04],
  'name'        :   ["bernard"],
  'gender'      :   ["gent"],
  'picture'     :   ["pictures/bernard.png"],
  'head'        :   ["oval"],
  'nose'        :   ["extra large"],
  'ears'        :   ["big"],
  'eyes'        :   ["brow", "normal eyebrows"],
  'cheeks'      :   ["none"],
  'chin'        :   ["dimple"],
  'mouth'       :   ["narrow", "small lips"], 
  'hair'        :   ["brown","short"],
  'expresion'   :   ["grumpy"],
  'facial hair' :   ["none"],
  'accessories' :   ["hat"]  
},
{
  'id'          :   [05],
  'name'        :   ["bill"],
  'gender'      :   ["gent"],
  'picture'     :   ["pictures/bill.png"],
  'head'        :   ["egg shaped"],
  'nose'        :   ["small"],
  'ears'        :   ["normal"],
  'eyes'        :   ["brown", "normal eyebrows"],
  'cheeks'      :   ["rosy"],
  'chin'        :   ["none"],
  'mouth'       :   ["narrow", "small lips"], 
  'hair'        :   ["ginger","bald"],
  'expresion'   :   ["happy"],
  'facial hair' :   ["beard"],
  'accessories' :   ["none"]  
},
{
  'id'          :   [06],
  'name'        :   ["charles"],
  'gender'      :   ["gent"],
  'picture'     :   ["pictures/charles.png"],
  'head'        :   ["round"],
  'nose'        :   ["medium"],
  'ears'        :   ["big"],
  'eyes'        :   ["brown", "normal eyebrows"],
  'cheeks'      :   ["none"],
  'chin'        :   ["round"],
  'mouth'       :   ["wide", "big lips"], 
  'hair'        :   ["blonde","short"],
  'expresion'   :   ["happy"],
  'facial hair' :   ["moustache"],
  'accessories' :   ["none"]  
},
{
  'id'          :   [07],
  'name'        :   ["claire"],
  'gender'      :   ["lady"],
  'picture'     :   ["pictures/claire.png"],
  'head'        :   ["oval"],
  'nose'        :   ["small"],
  'ears'        :   ["none"],
  'eyes'        :   ["brown", "neat eyebrows"],
  'cheeks'      :   ["none"],
  'chin'        :   ["round"],
  'mouth'       :   ["narrow", "small lips"], 
  'hair'        :   ["ginger","short"],
  'expresion'   :   ["pout"],
  'facial hair' :   ["none"],
  'accessories' :   ["hat", "glasses"]  
},
{
  'id'          :   [08],
  'name'        :   ["david"],
  'gender'      :   ["gent"],
  'picture'     :   ["pictures/david.png"],
  'head'        :   ["long"],
  'nose'        :   ["small"],
  'ears'        :   ["big"],
  'eyes'        :   ["brown", "normal eyebrows"],
  'cheeks'      :   ["none"],
  'chin'        :   ["none"],
  'mouth'       :   ["wide", "small lips"], 
  'hair'        :   ["blonde","short"],
  'expresion'   :   ["happy"],
  'facial hair' :   ["beard"],
  'accessories' :   ["none"]  
},
{
  'id'          :   [09],
  'name'        :   ["eric"],
  'gender'      :   ["gent"],
  'picture'     :   ["pictures/eric.png"],
  'head'        :   ["square"],
  'nose'        :   ["small"],
  'ears'        :   ["normal"],
  'eyes'        :   ["brown", "normal eyebrows"],
  'cheeks'      :   ["none"],
  'chin'        :   ["dimple"],
  'mouth'       :   ["wide", "small lips"], 
  'hair'        :   ["blonde","short"],
  'expresion'   :   ["happy"],
  'facial hair' :   ["none"],
  'accessories' :   ["hat"]  
},
{
  'id'          :   [10],
  'name'        :   ["frans"],
  'gender'      :   ["gent"],
  'picture'     :   ["pictures/frans.png"],
  'head'        :   ["square"],
  'nose'        :   ["small"],
  'ears'        :   ["big"],
  'eyes'        :   ["brown", "bushy eyebrows"],
  'cheeks'      :   ["none"],
  'chin'        :   ["pointy"],
  'mouth'       :   ["narrow", "small lips"], 
  'hair'        :   ["ginger","short"],
  'expresion'   :   ["pout"],
  'facial hair' :   ["none"],
  'accessories' :   ["none"]  
},
{
  'id'          :   [11],
  'name'        :   ["george"],
  'gender'      :   ["gent"],
  'picture'     :   ["pictures/george.png"],
  'head'        :   ["round"],
  'nose'        :   ["medium"],
  'ears'        :   ["normal"],
  'eyes'        :   ["brown", "normal eyebrows"],
  'cheeks'      :   ["none"],
  'chin'        :   ["dimple"],
  'mouth'       :   ["wide", "small lips"], 
  'hair'        :   ["white","short"],
  'expresion'   :   ["said"],
  'facial hair' :   ["none"],
  'accessories' :   ["hat"]  
},
{
  'id'          :   [12],
  'name'        :   ["herman"],
  'gender'      :   ["gent"],
  'picture'     :   ["pictures/herman.png"],
  'head'        :   ["oval"],
  'nose'        :   ["extra large"],
  'ears'        :   ["normal"],
  'eyes'        :   ["brown", "bushy eyebrows"],
  'cheeks'      :   ["none"],
  'chin'        :   ["pointy"],
  'mouth'       :   ["narrow", "small lips"], 
  'hair'        :   ["ginger","bald"],
  'expresion'   :   ["neutral"],
  'facial hair' :   ["none"],
  'accessories' :   ["none"]  
},
{
  'id'          :   [13],
  'name'        :   ["joe"],
  'gender'      :   ["gent"],
  'picture'     :   ["pictures/joe.png"],
  'head'        :   ["oval"],
  'nose'        :   ["medium"],
  'ears'        :   ["normal"],
  'eyes'        :   ["brown", "bushy eyebrows"],
  'cheeks'      :   ["none"],
  'chin'        :   ["dimple"],
  'mouth'       :   ["narrow", "small lips"], 
  'hair'        :   ["blonde","short"],
  'expresion'   :   ["pout"],
  'facial hair' :   ["none"],
  'accessories' :   ["glasses"]  
},
{
  'id'          :   [14],
  'name'        :   ["maria"],
  'gender'      :   ["lady"],
  'picture'     :   ["pictures/maria.png"],
  'head'        :   ["oval"],
  'nose'        :   ["medium"],
  'ears'        :   ["none"],
  'eyes'        :   ["brown", "neat eyebrows"],
  'cheeks'      :   ["none"],
  'chin'        :   ["round"],
  'mouth'       :   ["wide", "small lips"], 
  'hair'        :   ["brown","long"],
  'expresion'   :   ["pout"],
  'facial hair' :   ["none"],
  'accessories' :   ["hat", "earring"]  
},
{
  'id'          :   [15],
  'name'        :   ["max"],
  'gender'      :   ["gent"],
  'picture'     :   ["pictures/max.png"],
  'head'        :   ["round"],
  'nose'        :   ["extra large"],
  'ears'        :   ["normal"],
  'eyes'        :   ["brown", "normal eyebrows"],
  'cheeks'      :   ["none"],
  'chin'        :   ["none"],
  'mouth'       :   ["wide", "big lips"], 
  'hair'        :   ["black","short"],
  'expresion'   :   ["happy"],
  'facial hair' :   ["moustache"],
  'accessories' :   ["none"]  
},
{
  'id'          :   [16],
  'name'        :   ["paul"],
  'gender'      :   ["gent"],
  'picture'     :   ["pictures/paul.png"],
  'head'        :   ["oval"],
  'nose'        :   ["small"],
  'ears'        :   ["big"],
  'eyes'        :   ["brown", "normal eyebrows"],
  'cheeks'      :   ["none"],
  'chin'        :   ["dimple"],
  'mouth'       :   ["narrow", "small lips"], 
  'hair'        :   ["white","short"],
  'expresion'   :   ["happy"],
  'facial hair' :   ["none"],
  'accessories' :   ["glasses"]  
},
{ 
  'id'          :   [17],
  'name'        :   ["peter"],
  'gender'      :   ["gent"],
  'picture'     :   ["pictures/peter.png"],
  'head'        :   ["square"],
  'nose'        :   ["extra large"],
  'ears'        :   ["normal"],
  'eyes'        :   ["blue", "bushy eyebrows"],
  'cheeks'      :   ["none"],
  'chin'        :   ["pointy"],
  'mouth'       :   ["wide", "big lips"], 
  'hair'        :   ["white","short"],
  'expresion'   :   ["happy"],
  'facial hair' :   ["none"],
  'accessories' :   ["none"]  
},
{
  'id'          :   [18],
  'name'        :   ["philip"],
  'gender'      :   ["gent"],
  'picture'     :   ["pictures/philip.png"],
  'head'        :   ["round"],
  'nose'        :   ["medium"],
  'ears'        :   ["normal"],
  'eyes'        :   ["brown", "need eyebrows"],
  'cheeks'      :   ["rosy"],
  'chin'        :   ["none"],
  'mouth'       :   ["wide", "small lips"], 
  'hair'        :   ["black","short"],
  'expresion'   :   ["happy"],
  'facial hair' :   ["beard"],
  'accessories' :   ["none"]  
},{
  'id'          :   [19],
  'name'        :   ["richard"],
  'gender'      :   ["gent"],
  'picture'     :   ["pictures/richard.png"],
  'head'        :   ["long"],
  'nose'        :   ["medium"],
  'ears'        :   ["normal"],
  'eyes'        :   ["brown", "normal eyebrows"],
  'cheeks'      :   ["none"],
  'chin'        :   ["none"],
  'mouth'       :   ["narrow", "small lips"], 
  'hair'        :   ["brown","bald"],
  'expresion'   :   ["neutral"],
  'facial hair' :   ["moustache", "beard"],
  'accessories' :   ["none"]  
},
{
  'id'          :   [20],
  'name'        :   ["robert"],
  'gender'      :   ["gent"],
  'picture'     :   ["pictures/robert.png"],
  'head'        :   ["oval"],
  'nose'        :   ["extra large"],
  'ears'        :   ["big"],
  'eyes'        :   ["bleu", "normal eyebrows"],
  'cheeks'      :   ["rosy"],
  'chin'        :   ["dimple"],
  'mouth'       :   ["wide", "small lips"], 
  'hair'        :   ["brown","short"],
  'expresion'   :   ["grumpy"],
  'facial hair' :   ["none"],
  'accessories' :   ["none"]   
},
{ 
  'id'          :   [21],
  'name'        :   ["sam"],
  'gender'      :   ["gent"],
  'picture'     :   ["pictures/sam.png"],
  'head'        :   ["round"],
  'nose'        :   ["medium"],
  'ears'        :   ["small"],
  'eyes'        :   ["brown", "need eyebrows"],
  'cheeks'      :   ["none"],
  'chin'        :   ["pointy"],
  'mouth'       :   ["small", "small lips"], 
  'hair'        :   ["white","bald"],
  'expresion'   :   ["happy"],
  'facial hair' :   ["none"],
  'accessories' :   ["glasses"]  
},
{
  'id'          :   [22],
  'name'        :   ["susan"],
  'gender'      :   ["lady"],
  'picture'     :   ["pictures/susan.png"],
  'head'        :   ["oval"],
  'nose'        :   ["small"],
  'ears'        :   ["none"],
  'eyes'        :   ["brown", "need eyebrows"],
  'cheeks'      :   ["rosy"],
  'chin'        :   ["round"],
  'mouth'       :   ["wide", "big lips"], 
  'hair'        :   ["white","long"],
  'expresion'   :   ["happy"],
  'facial hair' :   ["none"],
  'accessories' :   ["none"]  
},
{
  'id'          :   [23],
  'name'        :   ["tom"],
  'gender'      :   ["gent"],
  'picture'     :   ["pictures/tom.png"],
  'head'        :   ["long"],
  'nose'        :   ["medium"],
  'ears'        :   ["normal"],
  'eyes'        :   ["blue", "normal eyebrows"],
  'cheeks'      :   ["none"],
  'chin'        :   ["round"],
  'mouth'       :   ["narrow", "small lips"], 
  'hair'        :   ["black","bald"],
  'expresion'   :   ["happy"],
  'facial hair' :   ["none"],
  'accessories' :   ["glasses"]  
}];


